import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { TanStackProvider } from '@/context/TanStackProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: { icon: '/next.svg' },
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<TanStackProvider>{children}</TanStackProvider>
			</body>
		</html>
	);
};

export default RootLayout;
